"""Fitting engine for μSR data."""

from asymmetry.core.fitting import muon_fluorine, sc
from asymmetry.core.fitting.composite import COMPONENTS, ComponentDefinition, CompositeModel
from asymmetry.core.fitting.composite_parameters import (
    CompositeEvaluation,
    CompositeExpression,
    CompositeExpressionError,
    CompositeParameterDefinition,
    FunctionSpec,
    validate_composite_expression,
)
from asymmetry.core.fitting.engine import FitEngine
from asymmetry.core.fitting.field_scan import (
    ScanBaselineResult,
    as_composite_model,
    fit_scan_baseline,
    fit_scan_model,
    parameter_set_for_model,
)
from asymmetry.core.fitting.fit_quality import FitQuality, assess_fit_quality
from asymmetry.core.fitting.fit_wizard import (
    CandidateAssessment,
    CandidateTemplate,
    FitWizardRecommendation,
    SelectionMetric,
    SpectrumFingerprint,
    build_candidate_templates,
    build_fit_wizard_recommendation,
    compute_information_criteria,
    fingerprint_spectrum,
    rerank_fit_wizard_recommendation,
)
from asymmetry.core.fitting.global_fit_wizard import (
    GlobalCandidateAssessment,
    GlobalFitWizardCandidatePortfolio,
    GlobalFitWizardRecommendation,
    GlobalParameterRecommendation,
    build_global_fit_wizard_candidate_portfolio,
    build_global_fit_wizard_recommendation,
    build_global_fit_wizard_screening_recommendation,
    merge_global_fit_wizard_recommendations,
    rerank_global_fit_wizard_recommendation,
)
from asymmetry.core.fitting.grouped_time_domain import (
    GROUP_NUISANCE_PARAMS,
    GROUPED_SERIES_RELATIONSHIPS,
    GroupedSeriesFitResult,
    GroupedTimeDomainFitResult,
    GroupedTimeDomainGroup,
    build_grouped_count_model,
    build_grouped_time_domain_datasets,
    build_grouped_time_domain_groups,
    fit_grouped_series,
    fit_grouped_time_domain,
)
from asymmetry.core.fitting.models import MODELS
from asymmetry.core.fitting.parameter_models import (
    PARAMETER_MODEL_COMPONENTS,
    ErrorMode,
    ModelFitRange,
    ParameterCompositeModel,
    ParameterModelComponentDefinition,
    ParameterModelFit,
    ParameterModelFitResult,
    apply_error_mode,
    component_names_for_x,
    effective_range_bounds,
    evaluate_parameter_model_fit,
    fit_parameter_model,
    range_mask,
    validate_fit_windows,
    windows_mask,
)
from asymmetry.core.fitting.parameters import Parameter, ParameterSet, ParamInfo, get_param_info
from asymmetry.core.fitting.result_summary import fit_result_summary
from asymmetry.core.fitting.spectral import (
    FREQUENCY_COMPONENT_NAMES,
    append_frequency_field_derived_parameters,
    default_frequency_model,
    field_gauss_to_frequency_mhz,
    frequency_mhz_to_field_gauss,
    seed_peak_parameters_from_dataset,
)

__all__ = [
    "FitEngine",
    "SelectionMetric",
    "SpectrumFingerprint",
    "CandidateTemplate",
    "CandidateAssessment",
    "FitWizardRecommendation",
    "GlobalParameterRecommendation",
    "GlobalCandidateAssessment",
    "GlobalFitWizardCandidatePortfolio",
    "GlobalFitWizardRecommendation",
    "GROUP_NUISANCE_PARAMS",
    "GROUPED_SERIES_RELATIONSHIPS",
    "build_grouped_count_model",
    "build_grouped_time_domain_datasets",
    "build_grouped_time_domain_groups",
    "GroupedSeriesFitResult",
    "GroupedTimeDomainFitResult",
    "GroupedTimeDomainGroup",
    "fit_grouped_series",
    "compute_information_criteria",
    "fingerprint_spectrum",
    "build_candidate_templates",
    "build_fit_wizard_recommendation",
    "rerank_fit_wizard_recommendation",
    "build_global_fit_wizard_candidate_portfolio",
    "build_global_fit_wizard_screening_recommendation",
    "build_global_fit_wizard_recommendation",
    "merge_global_fit_wizard_recommendations",
    "rerank_global_fit_wizard_recommendation",
    "fit_grouped_time_domain",
    "fit_result_summary",
    "sc",
    "muon_fluorine",
    "MODELS",
    "COMPONENTS",
    "ComponentDefinition",
    "CompositeModel",
    "CompositeParameterDefinition",
    "CompositeExpression",
    "CompositeExpressionError",
    "CompositeEvaluation",
    "FunctionSpec",
    "validate_composite_expression",
    "ParameterModelComponentDefinition",
    "ParameterCompositeModel",
    "PARAMETER_MODEL_COMPONENTS",
    "ParameterModelFit",
    "ModelFitRange",
    "ParameterModelFitResult",
    "ErrorMode",
    "FitQuality",
    "apply_error_mode",
    "assess_fit_quality",
    "effective_range_bounds",
    "fit_parameter_model",
    "range_mask",
    "validate_fit_windows",
    "windows_mask",
    "evaluate_parameter_model_fit",
    "component_names_for_x",
    "fit_scan_baseline",
    "fit_scan_model",
    "parameter_set_for_model",
    "as_composite_model",
    "ScanBaselineResult",
    "ParamInfo",
    "get_param_info",
    "Parameter",
    "ParameterSet",
    "FREQUENCY_COMPONENT_NAMES",
    "append_frequency_field_derived_parameters",
    "default_frequency_model",
    "field_gauss_to_frequency_mhz",
    "frequency_mhz_to_field_gauss",
    "seed_peak_parameters_from_dataset",
]
