"""Fitting engine for μSR data."""

from asymmetry.core.fitting import muon_fluorine, sc
from asymmetry.core.fitting.composite import COMPONENTS, ComponentDefinition, CompositeModel
from asymmetry.core.fitting.composite_parameters import (
    CompositeEvaluation,
    CompositeExpression,
    CompositeExpressionError,
    CompositeParameterDefinition,
    FunctionSpec,
    validate_composite_expression,
)
from asymmetry.core.fitting.engine import FitEngine
from asymmetry.core.fitting.fit_wizard import (
    CandidateAssessment,
    CandidateTemplate,
    FitWizardRecommendation,
    SelectionMetric,
    SpectrumFingerprint,
    build_candidate_templates,
    build_fit_wizard_recommendation,
    compute_information_criteria,
    fingerprint_spectrum,
    rerank_fit_wizard_recommendation,
)
from asymmetry.core.fitting.global_fit_wizard import (
    GlobalCandidateAssessment,
    GlobalFitWizardCandidatePortfolio,
    GlobalFitWizardRecommendation,
    GlobalParameterRecommendation,
    build_global_fit_wizard_candidate_portfolio,
    build_global_fit_wizard_recommendation,
    build_global_fit_wizard_screening_recommendation,
    merge_global_fit_wizard_recommendations,
    rerank_global_fit_wizard_recommendation,
)
from asymmetry.core.fitting.grouped_time_domain import (
    GROUP_NUISANCE_PARAMS,
    GroupedTimeDomainFitResult,
    GroupedTimeDomainGroup,
    build_grouped_count_model,
    build_grouped_time_domain_datasets,
    build_grouped_time_domain_groups,
    fit_grouped_time_domain,
)
from asymmetry.core.fitting.models import MODELS
from asymmetry.core.fitting.parameter_models import (
    PARAMETER_MODEL_COMPONENTS,
    ModelFitRange,
    ParameterCompositeModel,
    ParameterModelComponentDefinition,
    ParameterModelFit,
    ParameterModelFitResult,
    component_names_for_x,
    evaluate_parameter_model_fit,
    fit_parameter_model,
)
from asymmetry.core.fitting.parameters import Parameter, ParameterSet, ParamInfo, get_param_info

__all__ = [
    "FitEngine",
    "SelectionMetric",
    "SpectrumFingerprint",
    "CandidateTemplate",
    "CandidateAssessment",
    "FitWizardRecommendation",
    "GlobalParameterRecommendation",
    "GlobalCandidateAssessment",
    "GlobalFitWizardCandidatePortfolio",
    "GlobalFitWizardRecommendation",
    "GROUP_NUISANCE_PARAMS",
    "build_grouped_count_model",
    "build_grouped_time_domain_datasets",
    "build_grouped_time_domain_groups",
    "GroupedTimeDomainFitResult",
    "GroupedTimeDomainGroup",
    "compute_information_criteria",
    "fingerprint_spectrum",
    "build_candidate_templates",
    "build_fit_wizard_recommendation",
    "rerank_fit_wizard_recommendation",
    "build_global_fit_wizard_candidate_portfolio",
    "build_global_fit_wizard_screening_recommendation",
    "build_global_fit_wizard_recommendation",
    "merge_global_fit_wizard_recommendations",
    "rerank_global_fit_wizard_recommendation",
    "fit_grouped_time_domain",
    "sc",
    "muon_fluorine",
    "MODELS",
    "COMPONENTS",
    "ComponentDefinition",
    "CompositeModel",
    "CompositeParameterDefinition",
    "CompositeExpression",
    "CompositeExpressionError",
    "CompositeEvaluation",
    "FunctionSpec",
    "validate_composite_expression",
    "ParameterModelComponentDefinition",
    "ParameterCompositeModel",
    "PARAMETER_MODEL_COMPONENTS",
    "ParameterModelFit",
    "ModelFitRange",
    "ParameterModelFitResult",
    "fit_parameter_model",
    "evaluate_parameter_model_fit",
    "component_names_for_x",
    "ParamInfo",
    "get_param_info",
    "Parameter",
    "ParameterSet",
]
