"""Frequency-domain view of a YBCO vortex-lattice TF μSR signal.

In the mixed state of a Type-II superconductor the TF μSR signal samples
the internal-field distribution P(B) generated by the vortex lattice. The
Fourier transform of A(t) is therefore — up to an envelope — equal to
P(B), and its canonical asymmetric shape (sharp van-Hove peak at low
field, long high-field tail toward the vortex cores) is the textbook
benchmark for Fourier-domain analysis in μSR (Brandt PRB 37, 2349, 1988;
Sonier RMP 72, 769, 2000; textbook Ch 8/9).

The scenario:

1. Loads the YBCO vortex-lattice dataset (full Run with F/B detector
   histograms + grouping).
2. Switches the workspace to the **Frequency** domain.
3. Triggers the Fourier compute path so the frequency plot panel shows
   the FFT alongside the Fourier control dock.
"""

from __future__ import annotations

from PySide6.QtCore import Qt
from PySide6.QtWidgets import QWidget

from ..data import make_ybco_vortex_lattice
from ._base import Scenario, register, _process_events_for


class FourierTfScenario(Scenario):
    name = "fourier_tf"
    description = "Frequency-domain panel showing a YBCO vortex-lattice P(B) line shape."
    size = (1500, 920)

    def build(self) -> QWidget:
        from asymmetry.gui.mainwindow import MainWindow

        window = MainWindow()
        window._on_fourier()
        window.resizeDocks(
            [window._dock_data_browser], [320], Qt.Orientation.Horizontal
        )

        dataset = make_ybco_vortex_lattice()
        window._data_browser.add_dataset(dataset)
        window._on_dataset_selected(dataset.run_number)
        _process_events_for(milliseconds=120)

        # Switch the central plot workspace to the Frequency domain so the
        # FFT view, not the time-domain signal, is on screen alongside the
        # Fourier control dock.
        window._on_domain_button_clicked("frequency")
        _process_events_for(milliseconds=80)

        # Pre-set the frequency view window onto the Larmor peak
        # (γ_μ·B_app ≈ 27.1 MHz for 200 mT) so the canonical asymmetric
        # vortex P(B) shape is recognisable rather than lost in a wide
        # near-empty axis. _on_compute_fourier honours these limits because
        # _sync_frequency_plot_for_run is invoked with preserve_x_limits=True.
        freq_panel = window._frequency_plot_panel
        center_mhz = GAMMA_MU_MHZ_PER_G * 2000.0
        _, _, y_min, y_max = freq_panel.get_view_limits()
        freq_panel.set_view_limits(
            center_mhz - 1.0, center_mhz + 1.5, y_min, y_max
        )
        _process_events_for(milliseconds=60)

        # Trigger the Fourier pipeline so the spectrum plot is populated.
        window._on_compute_fourier()
        _process_events_for(milliseconds=240)
        return window


# Local import alias kept inside the module to avoid leaking constants from
# the data layer to scenario imports elsewhere.
from ..data.archetypes import GAMMA_MU_MHZ_PER_G  # noqa: E402


register(FourierTfScenario())
