"""Frequency-domain view of a YBCO vortex-lattice TF μSR signal.

In the mixed state of a Type-II superconductor the TF μSR signal samples
the internal-field distribution P(B) generated by the vortex lattice. The
Fourier transform of A(t) is therefore — up to an envelope — equal to
P(B), and its canonical asymmetric shape (sharp van-Hove peak at low
field, long high-field tail toward the vortex cores) is the textbook
benchmark for Fourier-domain analysis in μSR (Brandt PRB 37, 2349, 1988;
Sonier RMP 72, 769, 2000; textbook Ch 8/9).

The scenario:

1. Loads the YBCO vortex-lattice dataset (full Run with F/B detector
   histograms + grouping).
2. Switches the workspace to the **Frequency** domain.
3. Triggers the Fourier compute path so the frequency plot panel shows
   the FFT alongside the Fourier control dock.
"""

from __future__ import annotations

import numpy as np
from PySide6.QtCore import Qt
from PySide6.QtWidgets import QWidget

from ..data import make_ybco_vortex_lattice
from ._base import Scenario, register, _process_events_for


class FourierTfScenario(Scenario):
    name = "fourier_tf"
    description = "Frequency-domain panel showing a YBCO vortex-lattice P(B) line shape."
    size = (1500, 920)

    def build(self) -> QWidget:
        from asymmetry.gui.mainwindow import MainWindow

        window = MainWindow()
        window._on_fourier()
        window.resizeDocks(
            [window._dock_data_browser], [320], Qt.Orientation.Horizontal
        )

        # Reduced statistics (n0) keep the FFT magnitude inside the frequency
        # view's displayable range: the axis-limit fields clamp at ±1e6, and a
        # full-statistics run peaks near 1.1e7 — set_view_limits silently
        # truncates there and the spectrum sits above the top of the axis
        # (tracked as a product fix; revert to the default n0 once the
        # frequency view can frame it).
        dataset = make_ybco_vortex_lattice(n0=3.0e4)
        window._data_browser.add_dataset(dataset)
        window._on_dataset_selected(dataset.run_number)
        _process_events_for(milliseconds=120)

        # Switch the central plot workspace to the Frequency domain so the
        # FFT view, not the time-domain signal, is on screen alongside the
        # Fourier control dock.
        window._on_domain_button_clicked("frequency")
        _process_events_for(milliseconds=80)

        # Frame the frequency view onto the Larmor peak
        # (γ_μ·B_app ≈ 27.1 MHz for 200 mT) so the canonical asymmetric
        # vortex P(B) shape is recognisable rather than lost in a wide
        # near-empty axis. _on_compute_fourier honours these limits because
        # _sync_frequency_plot_for_run is invoked with preserve_x_limits=True.
        freq_panel = window._frequency_plot_panel
        center_mhz = GAMMA_MU_MHZ_PER_G * 2000.0
        x_min, x_max = center_mhz - 1.0, center_mhz + 1.5

        # Trigger the Fourier pipeline so the spectrum plot is populated. The
        # panel's default y-limits are stale for a count-scale spectrum and
        # Auto-Y collapses to degenerate limits on non-negative data (its
        # masking is tuned for signed time-domain asymmetry), so the spectrum
        # is read back and framed explicitly from its in-window peak below.
        window._on_compute_fourier()

        # The recompute runs on a worker thread and its render lands via a
        # queued signal, so a fixed settle is a race: read too early and the
        # panel still holds the pre-compute placeholder trace (spanning only a
        # few MHz), and the completing render then re-applies the stale view
        # limits it preserved at compute time. Poll until the rendered spectrum
        # actually reaches the Larmor window before framing it.
        spectrum_x = spectrum_y = None
        for _ in range(100):  # bounded at ~10 s; typically well under 1 s
            _process_events_for(milliseconds=100)
            x = freq_panel._last_plot_time
            y = freq_panel._last_plot_asymmetry
            if x is not None and y is not None and len(x) and float(np.nanmax(x)) >= x_max:
                spectrum_x = np.asarray(x, dtype=float)
                spectrum_y = np.asarray(y, dtype=float)
                break
        if spectrum_x is None:
            raise RuntimeError("Fourier recompute did not render within 10 s")

        in_window = (spectrum_x >= x_min) & (spectrum_x <= x_max)
        peak = float(np.max(spectrum_y[in_window])) if np.any(in_window) else 1.0
        freq_panel.set_view_limits(x_min, x_max, -0.04 * peak, 1.10 * peak)
        _process_events_for(milliseconds=120)
        return window


# Local import alias kept inside the module to avoid leaking constants from
# the data layer to scenario imports elsewhere.
from ..data.archetypes import GAMMA_MU_MHZ_PER_G  # noqa: E402


register(FourierTfScenario())
