# -*- mode: python ; coding: utf-8 -*-

from __future__ import annotations

import os
import sys
from pathlib import Path


# SPECPATH points to the directory containing this spec file.
project_root = Path(SPECPATH).resolve().parent
src_dir = project_root / "src"
entry_script = src_dir / "asymmetry" / "gui" / "app.py"
resources_dir = src_dir / "asymmetry" / "resources"

# Build icons are generated by CI on each platform.
default_icon = project_root / "build" / "icons" / ("Asymmetry.icns" if sys.platform == "darwin" else "Asymmetry.ico")
icon_path = os.environ.get("PYI_ICON_PATH", str(default_icon))
if not Path(icon_path).is_file():
    icon_path = None

datas = [(str(png_file), "asymmetry/resources") for png_file in resources_dir.glob("*.png")]

hiddenimports = [
    "h5py",
    "h5py._errors",
    "gleplot",
    "PySide6.QtSvg",
    "matplotlib.backends.backend_qtagg",
    "scipy.special._cdflib",
]

a = Analysis(
    [str(entry_script)],
    pathex=[str(src_dir)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["pytest", "ruff", "sphinx", "tkinter", "unittest"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Asymmetry",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    icon=icon_path,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="Asymmetry",
)

if sys.platform == "darwin":
    app = BUNDLE(
        coll,
        name="Asymmetry.app",
        icon=icon_path if icon_path and icon_path.endswith(".icns") else None,
        bundle_identifier="io.github.benhuddart.asymmetry",
    )