# -*- mode: python ; coding: utf-8 -*-

from __future__ import annotations

import os
import sys
from pathlib import Path

from PyInstaller.utils.hooks import collect_dynamic_libs, copy_metadata


# SPECPATH points to the directory containing this spec file.
project_root = Path(SPECPATH).resolve().parent
src_dir = project_root / "src"
entry_script = src_dir / "asymmetry" / "gui" / "app.py"
resources_dir = src_dir / "asymmetry" / "resources"

# Build icons are generated by CI on each platform.
default_icon = project_root / "build" / "icons" / ("Asymmetry.icns" if sys.platform == "darwin" else "Asymmetry.ico")
icon_path = os.environ.get("PYI_ICON_PATH", str(default_icon))
if not Path(icon_path).is_file():
    icon_path = None

datas = copy_metadata("asymmetry")
datas += [(str(png_file), "asymmetry/resources") for png_file in resources_dir.glob("*.png")]
datas += [(str(svg_file), "asymmetry/resources") for svg_file in resources_dir.glob("*.svg")]
fonts_dir = resources_dir / "fonts"
if fonts_dir.is_dir():
    datas += [(str(f), "asymmetry/resources/fonts") for f in fonts_dir.glob("*.ttf")]
    ofl = fonts_dir / "OFL.txt"
    if ofl.is_file():
        datas += [(str(ofl), "asymmetry/resources/fonts")]
styles_dir = src_dir / "asymmetry" / "gui" / "styles"
if styles_dir.is_dir():
    datas += [(str(f), "asymmetry/gui/styles") for f in styles_dir.glob("*.qss")]

# Ship the bundled-binary third-party license notices (HDF4 et al.) next to the
# app, as the HDF4 BSD-3 license requires for binary redistributions.
third_party_licenses = project_root / "THIRD_PARTY_LICENSES.md"
if third_party_licenses.is_file():
    datas += [(str(third_party_licenses), ".")]

hiddenimports = [
    "h5py",
    "h5py._errors",
    "gleplot",
    "PySide6.QtSvg",
    "matplotlib.backends.backend_qtagg",
    "scipy.special._cdflib",
    # pyhdf is imported lazily inside asymmetry.core.io.hdf4._require_pyhdf, so
    # PyInstaller's static analysis misses it; list its submodules explicitly.
    "pyhdf",
    "pyhdf.HDF",
    "pyhdf.SD",
    "pyhdf.V",
    "pyhdf.VS",
    "pyhdf.error",
    "pyhdf.hdfext",
]

binaries = collect_dynamic_libs("awkward_cpp")

# HDF4 read support (asymmetry[hdf4]). On macOS/Linux the pyhdf wheel bundles
# the HDF4 C library next to its extension, so collect it. On Windows the wheel
# ships only the extension; the HDF4 runtime (hdf.dll/mfhdf.dll + deps) is
# staged into ASYMMETRY_HDF4_DLL_DIR at build time (packaging/windows/
# fetch_hdf4_dlls.py) and bundled here so the frozen app reads HDF4 .nxs files
# out of the box. The loader registers the bundle dir via os.add_dll_directory
# (see asymmetry.core.io.hdf4._register_hdf4_runtime).
try:
    binaries += collect_dynamic_libs("pyhdf")
except Exception:  # pyhdf not installed in this build environment
    pass
_hdf4_dll_dir = os.environ.get("ASYMMETRY_HDF4_DLL_DIR")
if sys.platform == "win32" and _hdf4_dll_dir and Path(_hdf4_dll_dir).is_dir():
    binaries += [(str(dll), ".") for dll in Path(_hdf4_dll_dir).glob("*.dll")]

a = Analysis(
    [str(entry_script)],
    pathex=[str(src_dir)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["pytest", "ruff", "sphinx", "tkinter"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Asymmetry",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    icon=icon_path,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="Asymmetry",
)

if sys.platform == "darwin":
    app = BUNDLE(
        coll,
        name="Asymmetry.app",
        icon=icon_path if icon_path and icon_path.endswith(".icns") else None,
        bundle_identifier="io.github.benhuddart.asymmetry",
    )